### ISSUE TITLE
Adding a path with a space in it does not work

### ISSUE THREAD

**Issue by ehmiiz** [endowdly/GoPS#1]
Hey mate! Love the module so far!
Just FYI, tested this and got around it at last:

This added only "C:\Program" as path
0.048 Add-NavigationEntry module -Path C:\Program Files\PowerShell\Modules
  26        0.015 Add-NavigationEntry module -Path "C:\Program Files\PowerShell\Modules"
  27        0.027 Remove-NavigationEntry module
  28        0.012 Add-NavigationEntry module -Path 'C:\Program Files\PowerShell\Modules'
  29        0.005 Remove-NavigationEntry module
  30        0.004 $env:PSModulePath
  31        0.014 $env:PSModulePath.split(";")

(Work-around) This worked
  32        0.011 $env:PSModulePath.split(";")[1]
  33        0.012 Add-NavigationEntry modules $env:PSModulePath.split(";")[1]

Cheers for the module!

**Comment by ehmiiz** [comment]
I realized it works good if I close the path with /
So this can be closed!

**Comment by endowdly** [comment]
- I suspect this is caused with my use of `System.IO.DirectoryInfo` to roughly/quickly validate incoming path strings
-  I will hopefully have time to poke around this weekend to confirm this--if I'm correct, I should be able to fix it so it's more accepting of not-fullname path strings
-  I strongly suspect this will fix this issue so users can enter paths like `C:\Program Files\PowerShell\Modules` without having to jump through hoops or close with a slash. 

I almost always add my paths with `$pwd`, which adds the fullname path to the record. Didn't think past that very well!

This issue will stay open until I get to the bottom of this, because it is not intended behavior. :)

**Comment by endowdly** [comment]
Fixed!

Tactically inserted `Convert-Path` to qualify valid paths.

If you understand how `Convert-Path` works, it'll even qualify simple local paths. 
For example, say you are in `C:\Program Files\PowerShell`: 

```powershell
addgo mods Modules
``` 

...should now work.

Also changed how jumping works in `Invoke-GoPS` to mirror this behavior.

Say you are in `C:\Program Files\Modules` and you have the modules `GoPS` and `PSReadline` present:

```powershell
go gops
``` 

...will set your location to `C:\Program Files\Modules\GoPS` _unless_ gops is a jumptoken in your database. In which case, you will be taken to the path it represents.
