### ISSUE TITLE
Installed and not working

### ISSUE THREAD

**Issue by iguyking** [endowdly/GoPS#2]
Using Powershell Core 7.1.3

Followed the instructions for install

When running `Import-Module gops` it comes back with "WARNING:" and that's it.  

```
❯ Get-JumpHistory

Jump Name         FullName
---- ----         --------
   1 kingdom-home C:\Users\iguy\Desktop\git\kingdom-home
   2 kingdom-home C:\Users\iguy\Desktop\git\kingdom-home
   3 Modules      C:\Users\iguy\Documents\Powershell\Modules


Desktop/git/kingdom-home
❯ go kingdom-home
Convert-Path: C:\Users\iguy\Documents\PowerShell\Modules\gops\gops.psm1:248
Line |
 248 |      $s1 = Convert-Path $s
     |            ~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\iguy\Desktop\git\kingdom-home\kingdom-home' because it does not exist.
     
```

What commands do I need to do for initial setup and usage?

**Comment by endowdly** [comment]
The first issue you are getting is interesting to me. I think that's something I need to patch because that sounds/smells like my resource file has a typo and the internal `Import-NavigationFile` function isn't getting the right message. 

The second issue is -- you aren't getting the right warning that tells you to create a navigation file because the default file doesn't exist (and shouldn't on your initial import). I have these steps outline in the readme, but it's a little outdated. 

Even with your patch, this should work: 

1. Import-Module GoPS
2. New-NavigationFile # No params needed unless you don't want the file stored at ~/.gops (optional)
3. Add-NavigationEntry kingdom-home ~/Desktop/git/kingdom-home  # alias addgo
4. Invoke-GoPS kingdom-home  # alias go

If you want to save your entry for use in sessions after you close your terminal, use `Export-NavigationEntry` without any parameters.
It will push your entries in memory to the navigation file you (optionally) created.

`home` should be added whenever you create a blank navigation file. Access your Entry objects with `Get-NavigationEntry`. After you create kingdom-home, try `go home`, then `go kingdom-home`. 

Jumping to directory names in the JumpHistory is a very interesting idea and I'm glad you tried it! I think that's a cool feature I should add in the future.

**Comment by endowdly** [comment]
I quickly patched up that missing warning. 
If you have time, please try to reinstall from the master and follow the steps I provided.

If everything works after that, I'll close!

**Comment by iguyking** [comment]
That's working now.  Thanks.
